# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Fraser Lab"
email: "jfraser@fraserlab.com"
description: "This is the official web page for the James Fraser Lab at UCSF."
twitter_username: fraser_lab
github_username: fraser-lab
# minimal_mistakes_skin: default
# search: true

url: "http://fraserlab.com"

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
# remote_theme: mmistakes/minimal-mistakes
# minimal_mistakes_skin: "mint"
# Outputting
permalink: pretty
paginate: 5 # amount of posts to show
paginate_path: "news/page:num"
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# defaults:
#   # _posts
#   - scope:
#       path: ""
#       type: posts
#     values:
#       layout: single
#       author_profile: true
#       read_time: true
#       comments: false
#       share: true
#       related: true
#   # _pages
#   - scope:
#       path: "_pages"
#       type: pages
#     values:
#       layout: single
#       author_profile: false

collections:
        affiliates:
                output: true
        members:
                output: true
        publications:
                output: true
        reviews:
                output: true
        alumni:
                output: true
        sep:
                output: true
        visitors:
                output: true
        undergrads:
                output: true
        pets:
                output: true

# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/
